[package]
name = "CetusAggregatorV2"
version = "0.1.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
published-at = "0x3864c7c59a4889fec05d1aae4bc9dba5a0e0940594b424fbed44cb3f6ac4c032"
# published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.23.1", override = true }
SuiSystem = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-system", rev = "mainnet-v1.23.1", override = true }
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", subdir = "sui", rev = "mainnet-v1.23.1" }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "mainnet-v1.23.1" }
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/cetus_clmm", rev = "mainnet-v1.26.0", override = true }
DeepBook = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/deepbook", rev = "mainnet-v1.23.1" }
KriyaAmm = { local = "../../externals/kriya-amm" }
KriyaClmm = { local = "../../externals/kriya-clmm" }
FlowxClmm = { local = "../../externals/flowx-clmm" }
FlowxAMM = { local = "../../externals/flowx-amm" }
TurbosDex = { local = "../../externals/turbos-dex" }
AftermathAMM = { local = "../../externals/aftermath/aftermath-amm" }
ProtocolFeeVault = { local = "../../externals/aftermath/amm-protocol-fee-vault" }
InsuranceFund = { local = "../../externals/aftermath/amm-insurance-fund" }
ReferralVault = { local = "../../externals/aftermath/amm-referral-vault" }
StakingRefer = { local = "../../externals/aftermath/staking-refer" }
Afsui = { local = "../../externals/aftermath/staking" }
Hasui = { local = "../../externals/hasui" }
Vsui = { local = "../../externals/vsui" }
BlueMove = { local = "../../externals/bluemove" }
deepbookv3 = { local = "../../externals/deepbookv3-old/deepbook" }
token = { local = "../../externals/deepbookv3-old/token" }


[addresses]
cetus_aggregator_v2 = "0x52eae33adeb44de55cfb3f281d4cc9e02d976181c0952f5323648b5717b33934"
# cetus_aggregator_v2 = "0x0"
